import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import MainShell from "@/components/layout/MainShell";
import ScrollToTop from "@/components/layout/ScrollToTop";
import Footer from "@/components/layout/footer";
import { montserrat, playfairDisplay } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${playfairDisplay.variable} ${montserrat.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col bg-surface text-on-surface">
        <ScrollToTop />
        <Header />
        <MainShell>{children}</MainShell>
        <Footer />
      </body>
    </html>
  );
}
